# Generated by Django 4.2.7 on 2024-01-28 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_gl', models.CharField(max_length=200)),
                ('opis_gl', models.CharField(max_length=2000)),
                ('ans_1', models.CharField(max_length=100)),
                ('ans_2', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('count_1', models.IntegerField()),
                ('count_2', models.IntegerField()),
                ('count_all', models.IntegerField()),
                ('persent_1', models.FloatField()),
                ('persent_2', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
